### ISSUE TITLE
It forces virt-manager to deconnect

### ISSUE THREAD

**Issue by soig** [JonathonReinhart/spice-record#15]
Hi
Could it be possible to have both virt-manager & spice-record connecting to the same VM?
Else one can record with spice-record what he does in the VM with virt-manager…
See you

**Comment by JonathonReinhart** [comment]
Hi, thanks for the interest in my project.

Please see the [Notes on the README](https://github.com/JonathonReinhart/spice-record/blob/ff14a7d46fa3816aa72881dc9f31b3dc2b5459ca/README.md#notes) where it says:

> Currently, the spice server only supports a single client connection. When another connection is opened, the current one is disconnected. Thus, this utility is limited in its usability as it cannot record a user interacting with the VM, and only an automatic ongoing process. There is however, an experimental feature to enable [multiple concurrent connections](https://www.spice-space.org/multiple-clients.html) to a single spice server.

This is an unfortunate limitation of the server (i.e. QEMU) and there is nothing that this project can do to work around that.

**Comment by soig** [comment]
Humm you still need to fix the link so that it points to the correct https://www.spice-space.org/multiple-clients.html instead

**Comment by JonathonReinhart** [comment]
@soig Oops. I actually did already update it (18e0b19b9113c987988416b52c8e240364b756d0) but my permalink in this conversation pointed to the old version. I updated my comment above. :smiley:
